### ISSUE TITLE
strange logic

### ISSUE THREAD

**Issue by zahodinikola** [zahodinikola/SimpleForum#1]
i've encountered bug with evaluating logical expression in function isSubmitDisabled() in loginController.js. !(false&&false) = ..?false

**Comment by humanier** [comment]
See this[ comment](https://github.com/zahodinikola/SimpleForum/commit/33deae740e3fde6f85c6aae6c8b064a6be23268a#commitcomment-22435812) for resolution

**Comment by humanier** [comment]
I created snippet which shows how the same expression is evaluated differently based on what data type you for variables: string or bool.

http://js.do/code/156115
